name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build web app
      run: npm run build

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Initialize Capacitor (if needed)
      run: |
        if [ ! -f "capacitor.config.ts" ]; then
          npx cap init "InkRealm" "com.lovable.inkrealm" --web-dir=dist
        fi

    - name: Add Android platform
      run: |
        if [ ! -d "android" ]; then
          npx cap add android
        fi

    - name: Generate app icons (Android)
      run: |
        # Prepare source icon in expected location for capacitor-assets
        mkdir -p resources
        if [ -f "src/assets/app-icon.png" ]; then cp -f src/assets/app-icon.png main/icon.png; fi
        if [ -f "src/assets/app-icon.png" ]; then cp -f src/assets/app-icon.png main/icon.png; fi
        ls -la resources || true
        # Generate mipmap icons from main/icon.png
        npx capacitor-assets generate --android
        # Show where icons were placed (for debugging)
        ls -la android/app/src/main/res/mipmap-*/ || true

    - name: Set Android app name to "1991" (debug too)
      run: |
        # Force the launcher label for all variants
        if [ -f "android/app/src/main/res/values/strings.xml" ]; then
          sed -i 's|<string name="app_name">.*</string>|<string name="app_name">1991</string>|g' android/app/src/main/res/values/strings.xml
        fi
        # If a debug override exists, ensure it matches as well
        if [ -f "android/app/src/debug/res/values/strings.xml" ]; then
          sed -i 's|<string name="app_name">.*</string>|<string name="app_name"></string1991>|g' android/app/src/debug/res/values/strings.xml
        fi
        # Remove any debug suffixes that might alter the label
        if [ -f "android/app/build.gradle" ]; then
          sed -i 's/versionNameSuffix \".*\"/versionNameSuffix \"\"/g' android/app/build.gradle || true
          sed -i 's/applicationIdSuffix \".*\"/applicationIdSuffix \"\"/g' android/app/build.gradle || true
        fi

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Configure Java 21 for Android
      run: |
        set -e
        echo "Using JAVA_HOME: $JAVA_HOME"
        # Normalize Java 21 in app module (if present)
        if [ -f "android/app/build.gradle" ]; then
          sed -i 's/JavaVersion.VERSION_1_8/JavaVersion.VERSION_21/g' android/app/build.gradle || true
          sed -i 's/JavaVersion.VERSION_11/JavaVersion.VERSION_21/g' android/app/build.gradle || true
          sed -i 's/JavaVersion.VERSION_17/JavaVersion.VERSION_21/g' android/app/build.gradle || true
          sed -i 's/jvmTarget = "1.8"/jvmTarget = "21"/g' android/app/build.gradle || true
          sed -i 's/jvmTarget = "11"/jvmTarget = "21"/g' android/app/build.gradle || true
          sed -i 's/jvmTarget = "17"/jvmTarget = "21"/g' android/app/build.gradle || true
          sed -i 's/sourceCompatibility = JavaVersion.VERSION_1_8/sourceCompatibility = JavaVersion.VERSION_21/g' android/app/build.gradle || true
          sed -i 's/targetCompatibility = JavaVersion.VERSION_1_8/targetCompatibility = JavaVersion.VERSION_21/g' android/app/build.gradle || true
          sed -i 's/sourceCompatibility = JavaVersion.VERSION_11/sourceCompatibility = JavaVersion.VERSION_21/g' android/app/build.gradle || true
          sed -i 's/targetCompatibility = JavaVersion.VERSION_11/targetCompatibility = JavaVersion.VERSION_21/g' android/app/build.gradle || true
          sed -i 's/sourceCompatibility = JavaVersion.VERSION_17/sourceCompatibility = JavaVersion.VERSION_21/g' android/app/build.gradle || true
          sed -i 's/targetCompatibility = JavaVersion.VERSION_17/targetCompatibility = JavaVersion.VERSION_21/g' android/app/build.gradle || true
          sed -i 's/JavaLanguageVersion.of(17)/JavaLanguageVersion.of(21)/g' android/app/build.gradle || true
          sed -i 's/JavaLanguageVersion.of(11)/JavaLanguageVersion.of(21)/g' android/app/build.gradle || true
        fi

        # Normalize Java 21 in Capacitor Android module (if present after sync)
        if [ -f "android/capacitor/capacitor-android/build.gradle" ]; then
          sed -i 's/JavaVersion.VERSION_1_8/JavaVersion.VERSION_21/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/JavaVersion.VERSION_11/JavaVersion.VERSION_21/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/JavaVersion.VERSION_17/JavaVersion.VERSION_21/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/jvmTarget = "1.8"/jvmTarget = "21"/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/jvmTarget = "11"/jvmTarget = "21"/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/jvmTarget = "17"/jvmTarget = "21"/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/sourceCompatibility = JavaVersion.VERSION_1_8/sourceCompatibility = JavaVersion.VERSION_21/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/targetCompatibility = JavaVersion.VERSION_1_8/targetCompatibility = JavaVersion.VERSION_21/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/sourceCompatibility = JavaVersion.VERSION_11/sourceCompatibility = JavaVersion.VERSION_21/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/targetCompatibility = JavaVersion.VERSION_11/targetCompatibility = JavaVersion.VERSION_21/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/sourceCompatibility = JavaVersion.VERSION_17/sourceCompatibility = JavaVersion.VERSION_21/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/targetCompatibility = JavaVersion.VERSION_17/targetCompatibility = JavaVersion.VERSION_21/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/JavaLanguageVersion.of(17)/JavaLanguageVersion.of(21)/g' android/capacitor/capacitor-android/build.gradle || true
          sed -i 's/JavaLanguageVersion.of(11)/JavaLanguageVersion.of(21)/g' android/capacitor/capacitor-android/build.gradle || true
        fi

        # Force Gradle to use the configured JAVA_HOME (JDK 21)
        mkdir -p android
        if [ -f "android/gradle.properties" ]; then
          grep -q '^org.gradle.java.home=' android/gradle.properties || echo "org.gradle.java.home=$JAVA_HOME" >> android/gradle.properties
        else
          echo "org.gradle.java.home=$JAVA_HOME" > android/gradle.properties
        fi

    - name: Build APK
      run: |
        cd android
        ./gradlew -Dorg.gradle.java.home="$JAVA_HOME" --no-daemon assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: 1991-v3-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
